# Generated by Django 5.0.14 on 2026-03-28 07:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studentactivity',
            name='activity',
            field=models.ForeignKey(db_column='activity_id', on_delete=django.db.models.deletion.PROTECT, to='core.activity'),
        ),
        migrations.AlterField(
            model_name='studentactivity',
            name='student',
            field=models.ForeignKey(db_column='student_id', on_delete=django.db.models.deletion.CASCADE, related_name='participations', to='core.student'),
        ),
    ]
